#!/bin/bash

for py_file in $(find . -name "*.py")
do
    echo '+++++++++++++'
    echo $py_file
    time -p pythonw $py_file >> "$py_file.out"  
    rm "$py_file.out"
    echo '+++++++++++++'
done

# run the following to output all to file timing.txt
# { ./run_scripts ; } &>timing.txt 
